[package]
name = "noodles_wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
noodles = { path = "../noodles"}
wasm-bindgen = "0.2.0"
console_error_panic_hook = "0.1.7"