[package]
name = "noodles-py"

version = "0.1.0"
edition = "2024"

[lib]
name = "noodles_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = {version = "0.25.0", features = ["extension-module"]}
noodles = {path = "../noodles"}